package main

import (
	"fmt"

	ext "github.com/mus-format/ext-protobuf-go"
	"github.com/mus-format/mus-go/unsafe"
	"github.com/mus-format/mus-go/varint"
	"google.golang.org/protobuf/encoding/protowire"
)

// Here you can find serializers for DataV1 and DataV2.
//
// In fact, when implementing Protobuf encoding with mus-go, there is no need
// for types generated by protoc. It is enough to use simple types like this
// one:
//
// 	type DataV1 struct {
// 	 	Str     string
//	  Bool    bool
//    Int32   int32
//    Float64 float64
//    Slice   []int32
//    Time    Timestamp
//  }
//
// The content of this file should be generated.

// Serializers.
var (
	DataV1Protobuf = dataV1Protobuf{}
	DataV2Protobuf = dataV2Protobuf{}

	SliceProtobuf = ext.NewSliceProtobuf(varint.Int32)
)

// Protobuf tags of the DataV1 and DataV2 fields.
var (
	strFieldTag     = protowire.EncodeTag(1, protowire.BytesType)
	boolFieldTag    = protowire.EncodeTag(2, protowire.VarintType)
	int32FieldTag   = protowire.EncodeTag(3, protowire.Fixed32Type)
	float64FieldTag = protowire.EncodeTag(4, protowire.Fixed64Type)
	sliceFieldTag   = protowire.EncodeTag(5, protowire.BytesType)
	timeFieldTag    = protowire.EncodeTag(6, protowire.BytesType)
)

// dataV1Protobuf implements the mus.Serializer interface for DataV1.
type dataV1Protobuf struct{}

// Marshal marshals data using Protobuf encoding. Actually, there is nothing
// complicated here. For each field (like data.Str or data.Bool) it:
// 1. Marshals the tag.
// 2. Marshals the length of the value, if the field is a struct or slice.
// 3. Marshals the value.
func (s dataV1Protobuf) Marshal(data *DataV1, bs []byte) (n int) {
	if data.Str != "" {
		n += varint.Uint64.Marshal(strFieldTag, bs[n:])
		n += ext.String.Marshal(data.Str, bs[n:])
	}
	if data.Bool {
		n += varint.Uint64.Marshal(boolFieldTag, bs[n:])
		n += unsafe.Bool.Marshal(data.Bool, bs[n:])
	}
	if data.Int32 != 0 {
		n += varint.Uint64.Marshal(int32FieldTag, bs[n:])
		n += unsafe.Int32.Marshal(data.Int32, bs[n:])
	}
	if data.Float64 != 0 {
		n += varint.Uint64.Marshal(float64FieldTag, bs[n:])
		n += unsafe.Float64.Marshal(data.Float64, bs[n:])
	}
	if len(data.Slice) > 0 {
		n += varint.Uint64.Marshal(sliceFieldTag, bs[n:])
		n += SliceProtobuf.Marshal(data.Slice, bs[n:])
	}
	if data.Time != nil && (data.Time.Seconds != 0 || data.Time.Nanos != 0) {
		n += varint.Uint64.Marshal(timeFieldTag, bs[n:])
		n += ext.TimestampNativeProtobuf.Marshal(data.Time, bs[n:])
	}
	return
}

// Unmarshal unmarshals in a loop:
// 1. Field tag.
// 2. Length of the value, if the field is a struct or slice.
// 3. Value.
func (s dataV1Protobuf) Unmarshal(bs []byte) (data *DataV1, n int, err error) {
	var (
		n1  int
		l   = len(bs)
		tag uint64
	)
	data = &DataV1{}
	for n < l {
		tag, n1, err = varint.Uint64.Unmarshal(bs[n:])
		n += n1
		if err != nil {
			return
		}
		switch tag {
		case strFieldTag:
			data.Str, n1, err = ext.String.Unmarshal(bs[n:])
		case boolFieldTag:
			data.Bool, n1, err = unsafe.Bool.Unmarshal(bs[n:])
		case int32FieldTag:
			data.Int32, n1, err = unsafe.Int32.Unmarshal(bs[n:])
		case float64FieldTag:
			data.Float64, n1, err = unsafe.Float64.Unmarshal(bs[n:])
		case sliceFieldTag:
			data.Slice, n1, err = SliceProtobuf.Unmarshal(bs[n:])
		case timeFieldTag:
			data.Time, n1, err = ext.TimestampNativeProtobuf.Unmarshal(bs[n:])
		default:
			err = fmt.Errorf("unexpected tag %v", tag)
		}
		n += n1
		if err != nil {
			return
		}
	}
	return
}

func (s dataV1Protobuf) Size(data *DataV1) (size int) {
	if data.Str != "" {
		size += varint.Uint64.Size(strFieldTag)
		size += ext.String.Size(data.Str)
	}
	if data.Bool {
		size += varint.Uint64.Size(boolFieldTag)
		size += unsafe.Bool.Size(data.Bool)
	}
	if data.Int32 != 0 {
		size += varint.Uint64.Size(int32FieldTag)
		size += unsafe.Int32.Size(data.Int32)
	}
	if data.Float64 != 0 {
		size += varint.Uint64.Size(float64FieldTag)
		size += unsafe.Float64.Size(data.Float64)
	}
	if len(data.Slice) > 0 {
		size += varint.Uint64.Size(sliceFieldTag)
		size += SliceProtobuf.Size(data.Slice)
	}
	if data.Time != nil && (data.Time.Seconds != 0 || data.Time.Nanos != 0) {
		size += varint.Uint64.Size(timeFieldTag)
		size += ext.TimestampNativeProtobuf.Size(data.Time)
	}
	return
}

// dataV2Protobuf implements the mus.Serializer interface for DataV2.
type dataV2Protobuf struct{}

func (s dataV2Protobuf) Marshal(data *DataV2, bs []byte) (n int) {
	if data.Str != "" {
		n += varint.Uint64.Marshal(strFieldTag, bs[n:])
		n += ext.String.Marshal(data.Str, bs[n:])
	}
	if data.Int32 != 0 {
		n += varint.Uint64.Marshal(int32FieldTag, bs[n:])
		n += unsafe.Int32.Marshal(data.Int32, bs[n:])
	}
	if data.Float64 != 0 {
		n += varint.Uint64.Marshal(float64FieldTag, bs[n:])
		n += unsafe.Float64.Marshal(data.Float64, bs[n:])
	}
	if data.Time != nil && (data.Time.Seconds != 0 || data.Time.Nanos != 0) {
		n += varint.Uint64.Marshal(timeFieldTag, bs[n:])
		n += ext.TimestampNativeProtobuf.Marshal(data.Time, bs[n:])
	}
	return
}

func (s dataV2Protobuf) Unmarshal(bs []byte) (data *DataV2, n int, err error) {
	var (
		n1  int
		l   = len(bs)
		tag uint64
	)
	data = &DataV2{}
	for n < l {
		tag, n1, err = varint.Uint64.Unmarshal(bs[n:])
		n += n1
		if err != nil {
			return
		}
		switch tag {
		case strFieldTag:
			data.Str, n1, err = ext.String.Unmarshal(bs[n:])
		case boolFieldTag:
			// Bool field was removed in DataV2, so simply skip it here.
			n1, err = unsafe.Bool.Skip(bs[n:])
		case int32FieldTag:
			data.Int32, n1, err = unsafe.Int32.Unmarshal(bs[n:])
		case float64FieldTag:
			data.Float64, n1, err = unsafe.Float64.Unmarshal(bs[n:])
		case sliceFieldTag:
			// Slice field was remove in DataV2, so simply skip it here.
			n1, err = SliceProtobuf.Skip(bs[n:])
		case timeFieldTag:
			data.Time, n1, err = ext.TimestampNativeProtobuf.Unmarshal(bs[n:])
		default:
			err = fmt.Errorf("unexpected tag %v", tag)
		}
		n += n1
		if err != nil {
			return
		}
	}
	return
}

func (s dataV2Protobuf) Size(data *DataV2) (size int) {
	if data.Str != "" {
		size += varint.Uint64.Size(strFieldTag)
		size += ext.String.Size(data.Str)
	}
	if data.Int32 != 0 {
		size += varint.Uint64.Size(int32FieldTag)
		size += unsafe.Int32.Size(data.Int32)
	}
	if data.Float64 != 0 {
		size += varint.Uint64.Size(float64FieldTag)
		size += unsafe.Float64.Size(data.Float64)
	}
	if data.Time != nil && (data.Time.Seconds != 0 || data.Time.Nanos != 0) {
		size += varint.Uint64.Size(timeFieldTag)
		size += ext.TimestampNativeProtobuf.Size(data.Time)
	}
	return
}
